name: Generate SVG on Push

on:
  push:
    branches:
      - main

jobs:
  generate_svg:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python script
      run: python generator/recent_pr/get_pr.py  # Replace "your_script.py" with the name of your Python script

    - name: Commit changes
      run: |
        git config --global user.name "KKtheGhost"
        git config --global user.email "kivinsae@gmail.com"
        git add ./mini_boards/pr.svg
        git commit -m "update: PR.svg"
        git push